#!/usr/bin/env node

/**
 * OCR Setup Script
 * Automates the initial configuration for OCR functionality
 *
 * Usage: node setup-ocr.js
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (query) =>
  new Promise((resolve) => rl.question(query, resolve));

const COLORS = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  red: "\x1b[31m",
};

const log = {
  success: (msg) => console.log(`${COLORS.green}✓${COLORS.reset} ${msg}`),
  error: (msg) => console.log(`${COLORS.red}✗${COLORS.reset} ${msg}`),
  info: (msg) => console.log(`${COLORS.blue}ℹ${COLORS.reset} ${msg}`),
  warn: (msg) => console.log(`${COLORS.yellow}⚠${COLORS.reset} ${msg}`),
  header: (msg) => console.log(`\n${COLORS.bright}${msg}${COLORS.reset}`),
};

const envPath = path.join(process.cwd(), ".env.local");
const examplePath = path.join(process.cwd(), ".env.example");

async function main() {
  try {
    console.clear();
    log.header("🚀 OCR Configuration Setup");
    console.log(
      "\nThis script will help you set up the OCR functionality for BMI Portal.\n"
    );

    // Check if .env.local exists
    if (fs.existsSync(envPath)) {
      const overwrite = await question(
        `${COLORS.yellow}⚠${COLORS.reset} .env.local already exists. Overwrite? (y/n) `
      );
      if (overwrite.toLowerCase() !== "y") {
        log.info("Skipping setup.");
        rl.close();
        return;
      }
    }

    // Get API key
    log.header("1️⃣  OpenAI API Key");
    console.log("To get your API key:");
    console.log("1. Visit: https://platform.openai.com/api-keys");
    console.log('2. Click "Create new secret key"');
    console.log("3. Copy the key (displayed only once)");
    console.log("4. Paste it below\n");

    const apiKey = await question("Enter your OpenAI API key: ");

    if (!apiKey || apiKey.trim().length === 0) {
      log.error("API key cannot be empty");
      rl.close();
      return;
    }

    if (!apiKey.startsWith("sk-")) {
      log.warn(
        'API key should start with "sk-". Double-check before proceeding.'
      );
    }

    // Get API base (optional)
    log.header("2️⃣  Backend API Configuration (Optional)");
    const apiBase = await question(
      "Enter API base URL (default: http://localhost:3000/api): "
    );

    // Create .env.local
    let envContent = `# BMI Portal Environment Configuration
# Generated by OCR Setup Script

# OpenAI API Key for OCR Processing
VITE_OPENAI_API_KEY=${apiKey}

`;

    if (apiBase && apiBase.trim().length > 0) {
      envContent += `# Backend API Configuration
VITE_API_BASE=${apiBase}

`;
    }

    envContent += `# Note: Keep this file private and never commit to version control
# Add to .gitignore to prevent accidental commits
`;

    fs.writeFileSync(envPath, envContent);
    log.success(`.env.local created successfully`);

    // Check .gitignore
    log.header("3️⃣  Security Configuration");
    const gitignorePath = path.join(process.cwd(), ".gitignore");

    if (fs.existsSync(gitignorePath)) {
      const gitignoreContent = fs.readFileSync(gitignorePath, "utf-8");
      if (!gitignoreContent.includes(".env.local")) {
        fs.appendFileSync(
          gitignorePath,
          "\n# Environment files\n.env.local\n.env.*.local\n"
        );
        log.success(".env.local added to .gitignore");
      } else {
        log.info(".env.local already in .gitignore");
      }
    } else {
      log.warn(
        '.gitignore not found. Please manually add ".env.local" to .gitignore'
      );
    }

    // Final steps
    log.header("✅ Setup Complete!");
    console.log("\nNext steps:");
    console.log("1. Restart your development server: npm run dev");
    console.log("2. Visit the OCR documentation: ./OCR_QUICK_REFERENCE.md");
    console.log("3. Test with: npm run dev\n");

    console.log("Resources:");
    console.log("- Setup Guide: ./OCR_SETUP.md");
    console.log("- Quick Reference: ./OCR_QUICK_REFERENCE.md");
    console.log("- Backend Integration: ./OCR_BACKEND_INTEGRATION.md");
    console.log(
      "- Implementation Checklist: ./OCR_IMPLEMENTATION_CHECKLIST.md\n"
    );

    log.success("Your OCR system is ready to use!");
  } catch (error) {
    log.error(`Setup failed: ${error.message}`);
    console.error(error);
  } finally {
    rl.close();
  }
}

// Run setup
main();
