import React from "react";

const IconStub = ({ className = "", title = "" }) => (
  <svg className={className} viewBox="0 0 24 24" aria-hidden>
    <title>{title}</title>
    <rect width="24" height="24" fill="currentColor" opacity="0.08" />
  </svg>
);

const names = [
  "ErrorHexaIcon",
  "AlertHexaIcon",
  "MoreDotIcon",
  "DownloadIcon",
  "FileIcon",
  "GridIcon",
  "AudioIcon",
  "VideoIcon",
  "BoltIcon",
  "PlusIcon",
  "BoxIcon",
  "CloseIcon",
  "CheckCircleIcon",
  "AlertIcon",
  "InfoIcon",
  "ErrorIcon",
  "ArrowUpIcon",
  "FolderIcon",
  "ArrowDownIcon",
  "ArrowRightIcon",
  "GroupIcon",
  "BoxIconLine",
  "ShootingStarIcon",
  "DollarLineIcon",
  "TrashBinIcon",
  "AngleUpIcon",
  "AngleDownIcon",
  "PencilIcon",
  "CheckLineIcon",
  "CloseLineIcon",
  "ChevronDownIcon",
  "PaperPlaneIcon",
  "EnvelopeIcon",
  "LockIcon",
  "UserIcon",
  "CalenderIcon",
  "EyeIcon",
  "EyeCloseIcon",
  "TimeIcon",
  "CopyIcon",
  "ChevronLeftIcon",
  "UserCircleIcon",
  "TaskIcon",
  "ListIcon",
  "TableIcon",
  "PageIcon",
  "PieChartIcon",
  "BoxCubeIcon",
  "PlugInIcon",
  "DocsIcon",
  "MailIcon",
  "HorizontaLDots",
  "ChevronUpIcon",
  "ChatIcon",
  "AngleLeftIcon",
  "AngleRightIcon",
];

const exports = {};
names.forEach((n) => {
  exports[n] = (props) => <IconStub {...props} title={n} />;
});

export default exports;
export const {
  ErrorHexaIcon,
  AlertHexaIcon,
  MoreDotIcon,
  DownloadIcon,
  FileIcon,
  GridIcon,
  AudioIcon,
  VideoIcon,
  BoltIcon,
  PlusIcon,
  BoxIcon,
  CloseIcon,
  CheckCircleIcon,
  AlertIcon,
  InfoIcon,
  ErrorIcon,
  ArrowUpIcon,
  FolderIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  GroupIcon,
  BoxIconLine,
  ShootingStarIcon,
  DollarLineIcon,
  TrashBinIcon,
  AngleUpIcon,
  AngleDownIcon,
  PencilIcon,
  CheckLineIcon,
  CloseLineIcon,
  ChevronDownIcon,
  PaperPlaneIcon,
  EnvelopeIcon,
  LockIcon,
  UserIcon,
  CalenderIcon,
  EyeIcon,
  EyeCloseIcon,
  TimeIcon,
  CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  TaskIcon,
  ListIcon,
  TableIcon,
  PageIcon,
  PieChartIcon,
  BoxCubeIcon,
  PlugInIcon,
  DocsIcon,
  MailIcon,
  HorizontaLDots,
  ChevronUpIcon,
  ChatIcon,
  AngleLeftIcon,
  AngleRightIcon,
} = exports;
