import { ListPage } from "../../components/common/ListPage";
import PageMeta from "../../components/common/PageMeta";

const COLUMNS = [
  { header: "Statement ID", accessor: "statementId" },
  { header: "Period", accessor: "period" },
  { header: "Statement Date", accessor: "statementDate" },
  { header: "Generated at", accessor: "generatedAt" },
  { header: "Generated By", accessor: "generatedBy" },
];

export default function UserStatements() {
  return (
    <div>
      <PageMeta
        title="Account Statements - BMI Invoice Management System"
        description="View your account statements and financial records."
      />
      <ListPage
        resourceName="user/statements"
        columns={COLUMNS}
        title="My Account Statements"
        subtitle="View your financial statements and records"
      />
    </div>
  );
}
